; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Bedrock Cosmos"
#define MyAppVersion "1.1.2"
#define MyAppPublisher "Bedrock Cosmos"
#define MyAppURL "https://bedrock-cosmos.app/"
#define MyAppExeName "BedrockCosmos.exe"
#define MyAppAssocNamePack MyAppName + " Skin Pack"
#define MyAppAssocExtPack ".bcpack"
#define MyAppAssocKeyPack StringChange(MyAppAssocNamePack, " ", "") + MyAppAssocExtPack
#define MyAppAssocNamePersona MyAppName + " Persona Item"
#define MyAppAssocExtPersona ".bcpersona"
#define MyAppAssocKeyPersona StringChange(MyAppAssocNamePersona, " ", "") + MyAppAssocExtPersona
#define SourceDir "C:\BedrockCosmos\Launcher\BedrockCosmos"
#define BuildDir SourceDir + "\bin\Release"
#define TextsDir "C:\BedrockCosmos\Installer\Texts"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{139AF231-3F91-4712-87A0-86F7d0FCFEF5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile={#TextsDir}\TermsOfService\en_US.txt
InfoBeforeFile={#TextsDir}\CertificateAgreement\en_US.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\InnoSetup
OutputBaseFilename=BedrockCosmosSetup
SetupIconFile={#SourceDir}\Icon.ico
Compression=zip
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: "{#TextsDir}\TermsOfService\en_US.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\en_US.txt"
Name: "bengali"; MessagesFile: "{#TextsDir}\Other\Bengali.isl"; LicenseFile: "{#TextsDir}\TermsOfService\bn_BD.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\bn_BD.txt"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"; LicenseFile: "{#TextsDir}\TermsOfService\de_DE.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\de_DE.txt"
Name: "indonesian"; MessagesFile: "{#TextsDir}\Other\Indonesian.isl"; LicenseFile: "{#TextsDir}\TermsOfService\id_ID.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\id_ID.txt"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl";  LicenseFile: "{#TextsDir}\TermsOfService\ja_JP.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\ja_JP.txt"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"; LicenseFile: "{#TextsDir}\TermsOfService\ru_RU.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\ru_RU.txt"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"; LicenseFile: "{#TextsDir}\TermsOfService\es_ES.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\es_ES.txt"
Name: "ukranian"; MessagesFile: "compiler:Languages\Ukrainian.isl"; LicenseFile: "{#TextsDir}\TermsOfService\uk_UA.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\uk_UA.txt"
Name: "vietnamese"; MessagesFile: "{#TextsDir}\Other\Vietnamese.isl"; LicenseFile: "{#TextsDir}\TermsOfService\vi_VN.txt"; InfoBeforeFile: "{#TextsDir}\CertificateAgreement\vi_VN.txt"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#BuildDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\{#MyAppExeName}.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\AutoUpdater.NET.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\Background.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\BCPackIcon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\BouncyCastle.Crypto.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\BrotliSharpLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\DiscordRPC.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#BuildDir}\Microsoft.Web.WebView2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#BuildDir}\Microsoft.Web.WebView2.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#BuildDir}\Microsoft.Web.WebView2.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\Microsoft.Win32.Registry.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.IO.Pipelines.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Security.AccessControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Security.Principal.Windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Text.Encodings.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Text.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\Titanium.Web.Proxy.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\Texts\*"; DestDir: "{app}\Texts\"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Sets app name to be "Bedrock Cosmos" when referenced in Windows UIs
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "{#MyAppName}"; Flags: uninsdeletekey
; Allows BCPacks to be opened
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExtPack}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKeyPack}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKeyPack}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocNamePack}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKeyPack}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\BCPackIcon.ico,0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKeyPack}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
; Allows BCPersonas to be opened
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExtPersona}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKeyPersona}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKeyPersona}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocNamePersona}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKeyPersona}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\BCPackIcon.ico,0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKeyPersona}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
; Allows URIs to be opened
Root: HKA; Subkey: "Software\Classes\bedrockcosmos"; ValueType: "string"; ValueData: "Bedrock Cosmos"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\bedrockcosmos"; ValueType: "string"; ValueName: "URL Protocol"; ValueData: ""
Root: HKA; Subkey: "Software\Classes\bedrockcosmos\DefaultIcon"; ValueType: "string"; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\bedrockcosmos\shell\open\command"; ValueType: "string"; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\Bedrock Cosmos"